ignored-vulnerabilities:
    - id: GO-2026-4601
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-4601
    - id: GO-2026-4602
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-4602
    - id: GO-2026-4603
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-4603
    - id: GO-2026-4865
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-4865
    - id: GO-2026-4870
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-4870
    - id: GO-2026-4918
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-4918
    - id: GO-2026-4946
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-4946
    - id: GO-2026-4947
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-4947
    - id: GO-2026-4971
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-4971
    - id: GO-2026-4977
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-4977
    - id: GO-2026-4980
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-4980
    - id: GO-2026-4982
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-4982
    - id: GO-2026-4986
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-4986
    - id: GO-2026-5026
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-5026
    - id: GO-2026-5037
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-5037
    - id: GO-2026-5038
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-5038
    - id: GO-2026-5039
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-5039
    - id: GO-2026-5856
      silence-until: 2026-08-19
      info: https://pkg.go.dev/vuln/GO-2026-5856
    # Infinite loop on invalid input in golang.org/x/text
    # Found in: golang.org/x/text/unicode/norm@v0.32.0
    # Fixed in: golang.org/x/text/unicode/norm@v0.39.0
    - id: GO-2026-5970
      silence-until: 2026-08-28
      info: https://pkg.go.dev/vuln/GO-2026-5970
    # Vulnerabilities in the xDS RBAC authorization engine and the HTTP/2 transport server implementation in google.golang.org/grpc
    # Found in: google.golang.org/grpc/internal/transport@v1.79.3
    # Fixed in: google.golang.org/grpc/internal/transport@v1.82.1
    - id: GO-2026-6061
      silence-until: 2026-08-28
      info: https://pkg.go.dev/vuln/GO-2026-6061
