apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: health-service
  namespace: system
spec:
  ports:
  - name: health
    port: 8081
    protocol: TCP
    targetPort: health
  selector:
    control-plane: controller-manager
