apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: intel-usertier
objects:
- kind: UserTier
  apiVersion: toolchain.dev.openshift.com/v1alpha1
  metadata:
    name: intel
    namespace: ${NAMESPACE}
  spec:
    deactivationTimeoutDays: ${{DEACTIVATION_TIMEOUT_DAYS}}
parameters:
- name: NAMESPACE
# 2 months for now
- name: DEACTIVATION_TIMEOUT_DAYS
  value: "60"
