apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: basicdeactivationdisabled-code
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      che.eclipse.org/openshift-username: ${USERNAME}
      openshift.io/description: ${USERNAME}-code
      openshift.io/display-name: ${USERNAME}-code
      openshift.io/requester: ${USERNAME}
    labels:
      name: ${USERNAME}-code
    name: ${USERNAME}-code
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: rbac-edit
    namespace: ${USERNAME}-code
  rules:
    - apiGroups:
        - authorization.openshift.io
        - rbac.authorization.k8s.io
      resources:
        - roles
        - rolebindings
      verbs:
        - get
        - list
        - watch
        - create
        - update
        - patch
        - delete
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: user-rbac-edit
    namespace: ${USERNAME}-code
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: rbac-edit
  subjects:
    - kind: User
      name: ${USERNAME}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: user-edit
    namespace: ${USERNAME}-code
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: User
    name: ${USERNAME}
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: resource-limits
    namespace: ${USERNAME}-code
  spec:
    limits:
    - type: "Container"
      default:
        cpu: 1000m
        memory: 750Mi
      defaultRequest:
        cpu: 10m
        memory: 64Mi
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-same-namespace
    namespace: ${USERNAME}-code
  spec:
    podSelector: {}
    ingress:
    - from:
      - podSelector: {}
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-from-openshift-ingress
    namespace: ${USERNAME}-code
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: ingress
    podSelector: {}
    policyTypes:
    - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-from-openshift-monitoring
    namespace: ${USERNAME}-code
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: monitoring
    podSelector: {}
    policyTypes:
    - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-from-codeready-workspaces-operator
    namespace: ${USERNAME}-code
  spec:
    ingress:
      - from:
          - namespaceSelector:
              matchLabels:
                network.openshift.io/policy-group: codeready-workspaces
    podSelector: {}
    policyTypes:
      - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-from-other-user-namespaces
    namespace: ${USERNAME}-code
  spec:
    ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              name: ${USERNAME}-dev
        - namespaceSelector:
            matchLabels:
              name: ${USERNAME}-stage
    podSelector: {}
    policyTypes:
      - Ingress
parameters:
- name: USERNAME
  required: true