apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    provider: codeready-toolchain
  name: basic-code
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      openshift.io/description: ${USERNAME}-code
      openshift.io/display-name: ${USERNAME}-code
      openshift.io/requester: ${USERNAME}
    labels:
      provider: codeready-toolchain
    name: ${USERNAME}-code
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      provider: codeready-toolchain
    name: toolchain-code
    namespace: ${USERNAME}-code
  roleRef:
    name: edit
  subjects:
  - kind: User
    name: ${USERNAME}
parameters:
- name: USERNAME
  required: true