apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: base-spacerole-admin # name is used in e2e tests
objects:

# Rolebindings that grant permissions to the users in their own namespaces
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    namespace: ${NAMESPACE}
    name: rbac-edit
  rules:
    - apiGroups:
        - authorization.openshift.io
        - rbac.authorization.k8s.io
      resources:
        - roles
        - rolebindings
      verbs:
        - get
        - list
        - watch
        - create
        - update
        - patch
        - delete
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    namespace: ${NAMESPACE}
    name: ${SPACE_NAME}-rbac-edit
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: rbac-edit
  subjects:
    - kind: User
      name: ${SPACE_NAME}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    namespace: ${NAMESPACE}
    name: ${SPACE_NAME}-edit
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: User
    name: ${SPACE_NAME}

parameters:
- name: SPACE_NAME
  required: true
- name: NAMESPACE
  required: true