kind: Template
apiVersion: v1
metadata:
  name: base-tier
objects:
- kind: NSTemplateTier
  apiVersion: toolchain.dev.openshift.com/v1alpha1
  metadata:
    name: base
    namespace: ${NAMESPACE}
  spec:
    clusterResources:
      templateRef: ${CLUSTER_TEMPL_REF}
    deactivationTimeoutDays: ${{DEACTIVATION_TIMEOUT_DAYS}}
    namespaces:
      - templateRef: ${DEV_TEMPL_REF}
      - templateRef: ${STAGE_TEMPL_REF}
parameters:
- name: NAMESPACE
- name: CLUSTER_TEMPL_REF
- name: DEV_TEMPL_REF
- name: STAGE_TEMPL_REF
- name: DEACTIVATION_TIMEOUT_DAYS
  value: "30"
