apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: deactivate30-usertier
objects:
- kind: UserTier
  apiVersion: toolchain.dev.openshift.com/v1alpha1
  metadata:
    name: deactivate30
    namespace: ${NAMESPACE}
  spec:
    deactivationTimeoutDays: ${{DEACTIVATION_TIMEOUT_DAYS}}
parameters:
- name: NAMESPACE
- name: DEACTIVATION_TIMEOUT_DAYS
  value: "30"
