kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: toolchaincluster-host
subjects:
- kind: ServiceAccount
  name: toolchaincluster-host
roleRef:
  kind: Role
  name: toolchaincluster-host
  apiGroup: rbac.authorization.k8s.io
