---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: toolchaincluster-host
  namespace: {{.Namespace}}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: toolchaincluster-host
  namespace: {{.Namespace}}
rules:
- apiGroups:
  - toolchain.dev.openshift.com
  resources:
  - "*"
  verbs:
  - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: toolchaincluster-host
  namespace: {{.Namespace}}
subjects:
- kind: ServiceAccount
  name: toolchaincluster-host
roleRef:
  kind: Role
  name: toolchaincluster-host
  apiGroup: rbac.authorization.k8s.io
