kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: toolchaincluster-host
  namespace: toolchain-host-operator
rules:
- apiGroups:
  - toolchain.dev.openshift.com
  resources:
  - "bannedusers"
  - "masteruserrecords"
  - "notifications"
  - "nstemplatetiers"
  - "spaces"
  - "spacebindings"
  - "tiertemplates"
  - "toolchainconfigs"
  - "toolchainclusters"
  - "toolchainstatuses"
  - "usersignups"
  - "usertiers"
  - "proxyplugins"
  - "spaceprovisionerconfigs"
  verbs:
  - "*"
