apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: nstemplatetiers.toolchain.dev.openshift.com
spec:
  group: toolchain.dev.openshift.com
  names:
    kind: NSTemplateTier
    plural: nstemplatetiers
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            namespaces:
              description: The namespace templates
              items:
                properties:
                  revision:
                    description: The revision of the corresponding template
                    type: string
                  template:
                    description: Optional field. Used to specify a custom template
                    type: string
                  type:
                    description: 'The type of the namespace. For example: ide|cicd|stage|default'
                    type: string
                required:
                - type
                - revision
                type: object
              type: array
          required:
          - namespaces
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
