package assets

// NewAssets returns a new wrapper for the binary assets generated by go-bindata
func NewAssets(names func() []string, asset func(string) ([]byte, error)) Assets {
	return Assets{
		Names: names,
		Asset: asset,
	}
}

// Assets a wrapper for the binary assets
type Assets struct {
	Names func() []string
	Asset func(string) ([]byte, error)
}

// Names returns the name of the files
func (a Assets) GetNames() []string {
	return a.Names()
}

// Asset returns the content of the given file, or an error
func (a Assets) GetAsset(name string) ([]byte, error) {
	return a.Asset(name)
}
