apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: appstudio-env-tier
objects:
- kind: NSTemplateTier
  apiVersion: toolchain.dev.openshift.com/v1alpha1
  metadata:
    name: appstudio-env
    namespace: ${NAMESPACE}
  spec:
    clusterResources:
      templateRef: ${CLUSTER_TEMPL_REF}
    namespaces:
      - templateRef: ${ENV_TEMPL_REF}
    spaceRoles:
      admin:
        templateRef: ${ADMIN_TEMPL_REF}
      viewer:
        templateRef: ${VIEWER_TEMPL_REF}
parameters:
- name: NAMESPACE
- name: CLUSTER_TEMPL_REF
- name: ENV_TEMPL_REF
- name: ADMIN_TEMPL_REF
- name: VIEWER_TEMPL_REF
