apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: intellarge-tier
objects:
- kind: NSTemplateTier
  apiVersion: toolchain.dev.openshift.com/v1alpha1
  metadata:
    name: intellarge
    namespace: ${NAMESPACE}
  spec:
    clusterResources:
      templateRef: ${CLUSTER_TEMPL_REF}
    namespaces:
    - templateRef: ${DEV_TEMPL_REF}
    spaceRoles:
      admin:
        templateRef: ${ADMIN_TEMPL_REF}
parameters:
- name: NAMESPACE
- name: CLUSTER_TEMPL_REF
- name: DEV_TEMPL_REF
- name: ADMIN_TEMPL_REF
