apiVersion: toolchain.dev.openshift.com/v1alpha1
kind: RegistrationService
metadata:
  labels:
    provider: codeready-toolchain
  name: reg-service
  namespace: toolchain-host-operator
spec:
  envVars:
    IMAGE: 'quay.io/codeready-toolchain/registration-service:60d3b74'
    ENVIRONMENT: 'dev'
    REPLICAS: '4'
    AUTH_CLIENT_LIBRARY_URL: 'https://sso.prod-preview.openshift.io/auth/js/keycloak.js'
