package nstemplatetiers

// NewAssets returns a new wrapper for the binary assets generated by go-bindata
func NewAssets(names func() []string, asset func(string) ([]byte, error)) Assets {
	return Assets{
		names: names,
		asset: asset,
	}
}

// Assets a wrapper for the binary assets
type Assets struct {
	names func() []string
	asset func(string) ([]byte, error)
}

// Names returns the name of the files
func (a Assets) Names() []string {
	return a.names()
}

// Asset returns the content of the given file, or an error
func (a Assets) Asset(name string) ([]byte, error) {
	return a.asset(name)
}
