#!/usr/bin/env bash

indentList() {
    local INDENT="      "
    sed -e "s/^/${INDENT}/" \
        -e "1s/^${INDENT}/${INDENT:0:-2}- /"
  }

indentElement() {
    local INDENT="  "
    sed -e "s/^/${INDENT}/"
  }

PRJ_ROOT_DIR=${PRJ_ROOT_DIR:-$(git rev-parse --show-toplevel)}
#IMAGE_NAME=${IMAGE_NAME:-quay.io/matousjobanek/host:alpha}

NEXT_CSV_VERSION=0.0.1
CURRENT_CSV_VERSION=0.0.0
CRDS_DIR=${PRJ_ROOT_DIR}/deploy/crds
PKG_DIR=${PRJ_ROOT_DIR}/deploy/olm-catalog/host-operator
CSV_DIR=${PKG_DIR}/${NEXT_CSV_VERSION}

CURRENT_DIR=${PWD}
cd ${PRJ_ROOT_DIR}
operator-sdk olm-catalog gen-csv --csv-version ${NEXT_CSV_VERSION} --from-version ${CURRENT_CSV_VERSION} --update-crds
cd ${CURRENT_DIR}

#sed -i 's/kind: ""/kind: KubeFedCluster/g' ${CSV_DIRS[$index]}/*clusterserviceversion.yaml
#sed -i 's/name: ""/name: kubefedclusters.core.kubefed.io/g' ${CSV_DIRS[$index]}/*clusterserviceversion.yaml
#sed -i 's/version: ""/version: v1beta1\n      description: KubeFedCluster configures kubefed to be aware of a Kubernetes\n        cluster and encapsulates the details necessary to communicate with the cluster..\n      displayName: KubeFedCluster/g' ${CSV_DIRS[$index]}/*clusterserviceversion.yaml
sed -i ':a;N;$!ba;s/  replaces: host-operator.v0.0.0\n//g' ${CSV_DIR}/*clusterserviceversion.yaml
#sed -i "s|REPLACE_IMAGE|${IMAGE_NAME}|g" ${CSV_DIR}/*clusterserviceversion.yaml

NAME=${NAME:-codeready-toolchain-saas-host}
LOWERCASE=($(echo $NAME | tr '-' ' '))
DISPLAYNAME=${LOWERCASE[*]^}

PKG=$(cat ${PKG_DIR}/*host-operator.package.yaml | indentList "packageName")

echo "# This file was autogenerated by 'host-operator/olm/olm_catalog.sh'
# Do not edit it manually!
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: $NAME
  namespace: openshift-marketplace
spec:
  configMap: $NAME
  displayName: $DISPLAYNAME
  publisher: Red Hat
  sourceType: internal
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: $NAME
  namespace: openshift-marketplace
data:
  customResourceDefinitions: |-
$(for crd in `ls ${CRDS_DIR}/*crd.yaml`; do cat ${crd} | indentList "apiVersion"; done)
  clusterServiceVersions: |-
$(cat ${CSV_DIR}/*clusterserviceversion.yaml | indentList apiVersion)
  packages: |
$PKG" | sed 's/^  *$//' > ${PRJ_ROOT_DIR}/hack/deploy_csv.yaml