name: ci-check-gomod
on:
  pull_request:
    branches:
      - master
    paths:
      - 'go.mod'

jobs:
  gomodreplacements:
    name: go.mod replacements
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: check
      run: |
        if go list -m all | grep --color=never -E 'github.com/(codeready-toolchain|kubesaw)/.+\s*=>'; then
          echo "the above replacement(s) are not allowed in go.mod"
          exit 1
        fi
